# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Internal Build to Google Play"
  lane :internal do
    # ensure_git_status_clean
#     increment_version_code(
#         gradle_file_path: "./android/build.gradle",
#         #ext_constant_name: "test"
#         #app_folder_name:"app"
#     )
    gradle(
        # project_dir: "./android/",
        task: "clean assemble",
        build_type: "Release",
        flags: "-PbuildType=release",
        print_command_output: true
    )
    puts "AABs: #{Actions.lane_context[SharedValues::GRADLE_ALL_AAB_OUTPUT_PATHS]}"
    puts "AAB: #{Actions.lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}"
    upload_to_play_store(
        track: 'internal'
    )
    # git_commit(
    #     path: ['./android/app/versioning/app_version.properties'],
    #     message: 'Version Bump Android'
    # )
    # add_git_tag(
    #     grouping: "builds",
    #     prefix: "v"
    # )
    # push_to_git_remote
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end